language: C++ 
compiler: g++

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code && make all && ./tests
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code